name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          -
            dockerfile: Dockerfile
            platform: amd64
          -
            dockerfile: Dockerfile.armhf
            platform: armhf
          -
            dockerfile: Dockerfile.arm64
            platform: arm64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          platforms: linux/${{ matrix.platform }}
          push: true
          tags: mdhiggins/sonarr-sma:latest-${{ matrix.platform }}

  publish:
    runs-on: ubuntu-lastest
    needs: [docker]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Create manifests for DockerHub
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          docker manifest create \
          mdhiggins/sonarr-sma:latest \
          --amend mdhiggins/sonarr-sma:latest-amd64 \
          --amend mdhiggins/sonarr-sma:latest-armhf \
          --amend mdhiggins/sonarr-sma:latest-arm64
      -
        name: Push manifest to DockerHub
        run: |
          docker manifest push mdhiggins/sonarr-sma:latest
